### ISSUE TITLE
memcached auth

### ISSUE THREAD

**Issue by szepeviktor** [petermolnar/wp-ffpc#13]
Please consider supporting
http://redislabs.com/memcached-cloud
Redis Labs needs SASL auth for memcached.

Thank you!!

**Comment by szepeviktor** [comment]
Isn't it implemented??
https://github.com/petermolnar/wp-ffpc/blob/0da7a83f0eed0310639f67d6c9efe3120eb8da10/wp-ffpc-backend.php#L719

**Comment by petermolnar** [comment]
it was implemented a while ago, yes, however, I keep forgetting tracking the issues here; sorry about that.
