### ISSUE TITLE
When WP_CACHE is false, redirect_canonical is throwing a warning

### ISSUE THREAD

**Issue by haroldkyle** [petermolnar/wp-ffpc#14]
In our development environment we leave WP_CACHE at false yet leave the plugin active. This had done no harm, other than creating an admin notice in the administration area: "WP_CACHE is disabled, plugin will not work that way." When we upgraded to 1.3.1, this environment caused a PHP Warning on the front end:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp_ffpc_redirect_callback' not found or invalid function name 

This of course works fine when WP_CACHE is true. This go me to thinking that the plugin should not get so far on the front end if caching is indeed off. Not sure if this issue is worth addressing or not, but perhaps you should check if WP_CACHE is true before hooking some of the plugin_setup actions.

**Comment by jeffwidman** [comment]
Did this get handled?

**Comment by petermolnar** [comment]
This should be fixed.
