### ISSUE TITLE
Cached items not being set into Memcached

### ISSUE THREAD

**Issue by Xeoncross** [petermolnar/wp-ffpc#16]
I have the plugin installed and the nginx config for memcached running just fine. The site works great.

However, sitting here watching the memcached server stats I only see hits for "get" but the plugin doesn't seem to be calling "set" on the server to store the pages.

	STAT cmd_get 7
	STAT cmd_set 0
	STAT cmd_flush 0
	STAT cmd_touch 0
	STAT get_hits 0
	STAT get_misses 7
	STAT delete_misses 0
	STAT delete_hits 0
	....

So the nginx config keeps skipping loading from memcached (because there isn't anything in there) and keeps loading wordpress.

**Comment by petermolnar** [comment]
This should be fixed.
