### ISSUE TITLE
Question about post status hooks

### ISSUE THREAD

**Issue by Xeoncross** [petermolnar/wp-ffpc#28]
There is a function for [listening to post status changes](https://developer.wordpress.org/reference/hooks/old_status_to_new_status/) which you are using to [check for cache invalidation](https://github.com/petermolnar/wp-ffpc/blob/master/wp-ffpc-class.php#L179).

However, the code seems to be wrong. 

		foreach ( $post_types as $post_type ) {
			add_action( 'new_to_publish_' .$post_type , array( &$this->backend , 'clear' ), 0 );
			add_action( 'draft_to_publish' .$post_type , array( &$this->backend , 'clear' ), 0 );
			add_action( 'pending_to_publish' .$post_type , array( &$this->backend , 'clear' ), 0 );
			add_action( 'private_to_publish' .$post_type , array( &$this->backend , 'clear' ), 0 );
			add_action( 'publish_' . $post_type , array( &$this->backend , 'clear' ), 0 );
		}

Shouldn't the following be changed to this?

			add_action( 'new_to_publish' , array( &$this->backend , 'clear' ), 0 );
			add_action( 'draft_to_publish' , array( &$this->backend , 'clear' ), 0 );
			add_action( 'pending_to_publish' , array( &$this->backend , 'clear' ), 0 );
			add_action( 'private_to_publish' , array( &$this->backend , 'clear' ), 0 );

		foreach ( $post_types as $post_type ) {
			add_action( 'publish_' . $post_type , array( &$this->backend , 'clear' ), 0 );
		}

or even

		add_action(  'transition_post_status',  function($new, $old, $post) {... });

http://codex.wordpress.org/Post_Status_Transitions

**Comment by petermolnar** [comment]
Implemented.
