### ISSUE TITLE
Errors displayed even when Enable logging is off

### ISSUE THREAD

**Issue by haroldkyle** [petermolnar/wp-ffpc#35]
I just updated to WP-FFPC 1.7.7 and now all messages are being displaying in my development environment (where I display errors). Things like:

`Notice: PluginUtils – getting option wp-ffpc  in ... wp-common/plugin_utils.php on line 131`

In the past, I would deselect "Enable logging" in the WP-FFPC settings in order to quiet these, but this doesn't seem to have an effect anymore. It looks like you use `$this->utils->alert()` to display the filtered messages in `WP_FFPC::plugin_post_init()`. First, why not use `$this->log()` which would check the option value before displaying messages? But `PluginUtils::_get_option()` itself doesn't honor this option either, and will always display the notice above.

**Comment by petermolnar** [comment]
This is definitely not the expected behaviour and I know what is causing it.
I've separated the basic, shared functionality a while ago into a wp-common package and that does not respect the debug log flag from the settings. The only flag it does check is the WP_DEBUG static.

However, the alert() is only used for those that are actual issues and need to be addressed if the plugin is enabled; the log level for those is WARNING and they do not respect the WP_DEBUG flag, they always alert.

I'll try to come up with a solution for the noise but please disable WP_DEBUG and see if it eliminates it or not.

**Comment by haroldkyle** [comment]
Yeah, I know that turning off logging would quiet this, but I'm actually trying to find legitimate errors and I don't want WP-FFPC downing them out. 

Regarding alerts...I suppose this is another issue. This is happening in my development environment where I need to log errors and I can't have caching on. So, this combination throws an alert that I need to have WP_CACHE set to true. This didn't cause problems in previous versions, which I believe honored the Enable logging setting. And I can't disable the plugin entirely because other (cached) development repositories share this database.

**Comment by petermolnar** [comment]
I see.

I did change the aggressivity factor for those alerts because I realized they were not always visible enough. 

Let me think about a possible solution; I might try to introduce some "I know don't bother me again" button based solution, storing the user-preference for the notifications.

**Comment by haroldkyle** [comment]
Oh yeah, I like that idea.

**Comment by haroldkyle** [comment]
OK so as a solution, I see I can filter the errors array. This way I can keep errors from displaying on screen in my development environment where I don't use WP_CACHE and I display all errors.
```
add_filter('wp_ffpc_post_init_errors_array', function($errors){
	// if we have WP-FFPC errors in the development environment, we don't want to display them
	if( $errors && defined('DEVELOPMENT') && DEVELOPMENT){
		// I could squelch errors that I don't care about in development environment
		unset($errors['no_wp_cache']);

		// I could log these my own way...if I want to.
		foreach( $errors as $error ){
			error_log( $error );
		}

		// return nothing
		return array();
	}
});
```
