### ISSUE TITLE
Repo URL

### ISSUE THREAD

**Issue by szepeviktor** [petermolnar/wp-ffpc#42]
Please the repo URL here on GitHub to https://wordpress.org/plugins/wp-ffpc/
Thank you.

(The Edit link here: https://github.com/petermolnar/wp-ffpc )

**Comment by petermolnar** [comment]
hi,

I'm not entirely sure what you're asking me to do; also, this is the main repository. The WordPress SVN is horrifiying.

**Comment by szepeviktor** [comment]
This link here: ![Edit](http://i.snag.gy/8hW9K.jpg)

**Comment by szepeviktor** [comment]
:smile:
