### ISSUE TITLE
Make an exception (by page)

### ISSUE THREAD

**Issue by szepeviktor** [petermolnar/wp-ffpc#43]
Is there a way not to cache certain pages?

Like recognizing `<!--nocache-->` in the HTML.

**Comment by petermolnar** [comment]
There is a regex field in Cache exceptions tab which can be used for this.

**Comment by szepeviktor** [comment]
OK
I meant from the page's point of view.

**Comment by petermolnar** [comment]
No, there isn't. 
This never before was a required feature; obviously it can be done and it's not even that problematic.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by petermolnar** [comment]
the problem with this approach is that if the trigger is present in the post it will trigger when it's listed on a tag/category/taxonomy/whatever collection page as well, excluding the collection page also.

Is that the expected behaviour you're looking for?

**Comment by szepeviktor** [comment]
I could make up that option as a postmeta and emit it in the footer (which is not present on the archives).

**Comment by petermolnar** [comment]
rolled out in 1.9.0 as content regex match option.

**Comment by szepeviktor** [comment]
Thank you.

**Comment by szepeviktor** [comment]
@petermolnar Could you make a tagged release here?

**Comment by petermolnar** [comment]
done
