### ISSUE TITLE
WP object cache backend

### ISSUE THREAD

**Issue by szepeviktor** [petermolnar/wp-ffpc#53]
Hello @petermolnar !

As WP object caches are properly implemented (see for example `wp-redis`)
would it be possible to store the cache data in object cache?

**Comment by petermolnar** [comment]
No, it would not.

wp-ffpc is loaded **before** the WordPress functions, such as
wp_cache_add is loaded, so no, it's not possible.

**Comment by szepeviktor** [comment]
Thank you.

When fixing unstable redis backend please consider using code from
https://github.com/pantheon-systems/wp-redis/blob/master/object-cache.php#L252
